# MIAAM — per-student sequence preparation

This notebook processes the MIAAM/NeurIPS dataset of primary-school students completing adaptive math exercises and produces per-student interaction sequences for Knowledge Tracing experiments.

It outputs three parquet files into `../data/`:
- `sequences.parquet` — full dataset (~38 k students), one row per student; attempts stored as a chronologically ordered list of structs
- `train_sequences.parquet` — 80 % random split (seed 42)
- `val_sequences.parquet` — 20 % random split (seed 42)

Each attempt struct carries: `exercise_id_int`, `exercise_id`, `activity_id_int`, `activity_id`, `data_correct`, `created_at` (Unix seconds), `data_duration`, `work_mode`, `data_answer`, `session_id`, `module_name`.

## 1) Load MIAAM dataset

Loads the three source files from `../HF_neurips_official_dataset/`:
- `maths_data_filtered.parquet` — 36,837 students, 6,656,038 attempts (students with <5 attempts or adaptive-test-only histories excluded)
- `maths_exercises_table.parquet` — exercise metadata including hierarchy IDs (`objective_id`, `activity_id`, `module_id`) and text content
- `maths_dependencies.json` — activity-level pedagogical dependency graph

In [ ]:
import polars as pl
import json
import pathlib
import os
import numpy as np


DATASET = pathlib.Path("../../MIAAM")
SAVE_FOLDER = pathlib.Path("../data")

interactions = pl.read_parquet(DATASET / "data/maths_data_filtered.parquet")
exercises    = pl.read_parquet(DATASET / "data/maths_exercises_table.parquet")
deps         = json.loads((DATASET / "data/maths_dependencies.json").read_text())

print(interactions.shape, exercises.shape)

(6481693, 14) (7151, 12)

In [2]:
interactions.head(2)

shape: (2, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ user_id   ┆ classroom ┆ playlist_ ┆ exercise_ ┆ … ┆ attempt_i ┆ session_i ┆ module_id ┆ module_n │
│ ---       ┆ _id       ┆ or_module ┆ id        ┆   ┆ ndex      ┆ d         ┆ ---       ┆ ame      │
│ str       ┆ ---       ┆ _id       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆ ---       ┆ str       ┆   ┆ u32       ┆ str       ┆           ┆ str      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 36705bac- ┆ 58f3c4d4- ┆ 63e98e5f- ┆ 97516718- ┆ … ┆ 1         ┆ am::36705 ┆ 63e98e5f- ┆ Nombres  │
│ 0394-4d0a ┆ 01dc-4be9 ┆ 94e3-4630 ┆ fd8f-4f90 ┆   ┆           ┆ bac-0394- ┆ 94e3-4630 ┆ et       │
│ -8365-3be ┆ -8435-f7f ┆ -9704-076 ┆ -8ead-56d ┆   ┆           ┆ 4d0a-8365 ┆ -9704-076 ┆ calcul   │
│ 80a…      ┆ 46f…      ┆ 882…      ┆ ff6…      ┆   ┆           ┆ -3b…      ┆ 882…      ┆          │
│ 36705bac- ┆ 58f3c4d4- ┆ 63e98e5f- ┆ f90ab87b- ┆ … ┆ 1         ┆ am::36705 ┆ 63e98e5f- ┆ Nombres  │
│ 0394-4d0a ┆ 01dc-4be9 ┆ 94e3-4630 ┆ 7054-4de8 ┆   ┆           ┆ bac-0394- ┆ 94e3-4630 ┆ et       │
│ -8365-3be ┆ -8435-f7f ┆ -9704-076 ┆ -b836-300 ┆   ┆           ┆ 4d0a-8365 ┆ -9704-076 ┆ calcul   │
│ 80a…      ┆ 46f…      ┆ 882…      ┆ 653…      ┆   ┆           ┆ -3b…      ┆ 882…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
exercises.head(2)

shape: (2, 12)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ exercise_i ┆ gameplay_t ┆ content   ┆ module_id ┆ … ┆ activity_ ┆ activity_ ┆ activity_ ┆ source │
│ d          ┆ ype        ┆ ---       ┆ ---       ┆   ┆ id        ┆ name      ┆ pedagogic ┆ ---    │
│ ---        ┆ ---        ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ al_intent ┆ str    │
│ str        ┆ str        ┆           ┆           ┆   ┆ str       ┆ str       ┆ ---       ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆           ┆ str       ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ 39676249-7 ┆ INTERVAL_C ┆ {"instruc ┆ 63e98e5f- ┆ … ┆ 8e532d14- ┆ Toutes    ┆ Décompose ┆ am     │
│ 28a-4d21-9 ┆ OLORING    ┆ tion":    ┆ 94e3-4630 ┆   ┆ 06dc-45db ┆ tables    ┆ r toutes  ┆        │
│ a58-c31451 ┆            ┆ "[descrip ┆ -9704-076 ┆   ┆ -a1c9-bdf ┆           ┆ les       ┆        │
│ …          ┆            ┆ tion …    ┆ 882…      ┆   ┆ 4c7…      ┆           ┆ tables s… ┆        │
│ 1c921f06-1 ┆ MULTIPLE_C ┆ {"instruc ┆ 63e98e5f- ┆ … ┆ a8e9e045- ┆ Nombres   ┆ Comparer  ┆ am     │
│ 005-11ed-8 ┆ HOICE      ┆ tion":    ┆ 94e3-4630 ┆   ┆ c72f-4722 ┆ entre 60  ┆ des       ┆        │
│ 61d-0242ac ┆            ┆ "Clique   ┆ -9704-076 ┆   ┆ -bb0a-417 ┆ et 99     ┆ nombres   ┆        │
│ …          ┆            ┆ sur le…   ┆ 882…      ┆   ┆ 3d0…      ┆ (chiffr…  ┆ (représen ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆           ┆ …         ┆        │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

### Filter exercises without a screenshot

Some exercises in `maths_exercises_table.parquet` have no corresponding screenshot in `data/screenshots/compressed/`. They are removed from both `exercises` and `interactions` before any further processing, so that all remaining exercises have visual content available for multimodal models.

In [4]:
SCREENSHOTS = DATASET / "data/screenshots/compressed"
screenshot_ids = {
    f.stem
    for source_dir in SCREENSHOTS.iterdir()
    for f in source_dir.iterdir()
    if f.suffix == ".png"
}

missing_screenshots = exercises.filter(~pl.col("exercise_id").is_in(list(screenshot_ids)))
print(f"Exercises without a raw screenshot: {len(missing_screenshots)}")
print(missing_screenshots.select(["exercise_id", "source", "module_name", "activity_name"]))

exercises    = exercises.filter(pl.col("exercise_id").is_in(list(screenshot_ids)))
interactions = interactions.filter(pl.col("exercise_id").is_in(list(screenshot_ids)))
print(f"\nAfter filtering: {interactions.shape[0]} attempts, {interactions['exercise_id'].n_unique()} unique exercises")

Exercises without a raw screenshot: 12
shape: (12, 4)
┌─────────────────────────────────┬────────┬───────────────────┬─────────────────────────────────┐
│ exercise_id                     ┆ source ┆ module_name       ┆ activity_name                   │
│ ---                             ┆ ---    ┆ ---               ┆ ---                             │
│ str                             ┆ str    ┆ str               ┆ str                             │
╞═════════════════════════════════╪════════╪═══════════════════╪═════════════════════════════════╡
│ a84300cf-53ce-497d-aa20-1778f1… ┆ am     ┆ Nombres et calcul ┆ Table de 5                      │
│ fa2d0f28-0e2c-4d85-a1ef-0df785… ┆ am     ┆ Nombres et calcul ┆ Points disposés aléatoirement … │
│ 87fd4c76-c5dc-4cc4-b056-7096c5… ┆ am     ┆ Nombres et calcul ┆ Points disposés aléatoirement … │
│ e5fae336-e143-4070-b7f3-4ce23a… ┆ am     ┆ Nombres et calcul ┆ Table de 7                      │
│ 415808bf-9327-4e3a-a6af-694cf6… ┆ am     ┆ Nombres et calcul ┆ Chiffres et lettres (1 à 9)     │
│ …                               ┆ …      ┆ …                 ┆ …                               │
│ b9a89c6d-00cd-4989-aea2-a707eb… ┆ am     ┆ Nombres et calcul ┆ Constellations et chiffres (1 … │
│ f9a25ad9-fbcf-4a63-af9b-5b26a5… ┆ am     ┆ Nombres et calcul ┆ Table de 6                      │
│ 29b8593f-2fde-4253-813e-53e3f6… ┆ am     ┆ Nombres et calcul ┆ Table de 2                      │
│ 547e6741-602d-4be4-9fe4-03224a… ┆ am     ┆ Nombres et calcul ┆ Table de 8                      │
│ c2cacfff-be22-4e47-8907-675662… ┆ am     ┆ Nombres et calcul ┆ Points disposés aléatoirement … │
└─────────────────────────────────┴────────┴───────────────────┴─────────────────────────────────┘

After filtering: 6263671 attempts, 6936 unique exercises

## 2) Build per-student sequences

Enriches the attempt log with integer-encoded IDs and restructures it into per-student sequences suitable as input for Knowledge Tracing models. The result is a Polars DataFrame in parquet format — one row per student, all attempt fields collected into a parallel-list struct column ordered chronologically by `created_at`.

### Join exercise metadata

Join `activity_id` from the exercise table onto the attempt log using `exercise_id` as the key.

In [5]:
interactions = interactions.join(
    exercises.select(["exercise_id", "activity_id"]),
    on="exercise_id",
    how="left",
)

print(interactions.select(["exercise_id", "activity_id"]).head())

shape: (5, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ exercise_id                     ┆ activity_id                     │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ 97516718-fd8f-4f90-8ead-56dff6… ┆ 07144c8b-67d5-4596-b9e3-d49841… │
│ f90ab87b-7054-4de8-b836-300653… ┆ 0f54e38b-1a89-40aa-ad52-da52ba… │
│ f90ab87b-7054-4de8-b836-300653… ┆ 0f54e38b-1a89-40aa-ad52-da52ba… │
│ 21a30e28-d557-4760-a3dd-3838f4… ┆ 0f54e38b-1a89-40aa-ad52-da52ba… │
│ 21a30e28-d557-4760-a3dd-3838f4… ┆ 0f54e38b-1a89-40aa-ad52-da52ba… │
└─────────────────────────────────┴─────────────────────────────────┘

### Integer-encode IDs

KT models require contiguous integer indices for students, exercises, and skills (for which we use activities). Each UUID is mapped to a 0-based integer by sorting unique values alphabetically and assigning row indices — producing a stable mapping independent of the order of the interaction data.

In [6]:
user_id_map = (
    interactions.select("user_id")
    .unique()
    .sort("user_id")
    .with_row_index("user_id_int")
)

interactions = interactions.join(user_id_map, on="user_id", how="left")

print(f"{interactions['user_id_int'].n_unique()} unique students")
print(interactions.select(["user_id", "user_id_int"]).head())

38520 unique students
shape: (5, 2)
┌─────────────────────────────────┬─────────────┐
│ user_id                         ┆ user_id_int │
│ ---                             ┆ ---         │
│ str                             ┆ u32         │
╞═════════════════════════════════╪═════════════╡
│ 36705bac-0394-4d0a-8365-3be80a… ┆ 8097        │
│ 36705bac-0394-4d0a-8365-3be80a… ┆ 8097        │
│ 36705bac-0394-4d0a-8365-3be80a… ┆ 8097        │
│ 36705bac-0394-4d0a-8365-3be80a… ┆ 8097        │
│ 36705bac-0394-4d0a-8365-3be80a… ┆ 8097        │
└─────────────────────────────────┴─────────────┘

In [7]:
exercise_id_map = (
    interactions.select("exercise_id")
    .unique()
    .sort("exercise_id")
    .with_row_index("exercise_id_int")
)

interactions = interactions.join(exercise_id_map, on="exercise_id", how="left")

print(f"{interactions['exercise_id_int'].n_unique()} unique exercises")
print(interactions.select(["exercise_id", "exercise_id_int"]).head())

6936 unique exercises
shape: (5, 2)
┌─────────────────────────────────┬─────────────────┐
│ exercise_id                     ┆ exercise_id_int │
│ ---                             ┆ ---             │
│ str                             ┆ u32             │
╞═════════════════════════════════╪═════════════════╡
│ 97516718-fd8f-4f90-8ead-56dff6… ┆ 4022            │
│ f90ab87b-7054-4de8-b836-300653… ┆ 6723            │
│ f90ab87b-7054-4de8-b836-300653… ┆ 6723            │
│ 21a30e28-d557-4760-a3dd-3838f4… ┆ 1033            │
│ 21a30e28-d557-4760-a3dd-3838f4… ┆ 1033            │
└─────────────────────────────────┴─────────────────┘

In [8]:
activity_id_map = (
    interactions.select("activity_id")
    .unique()
    .sort("activity_id")
    .with_row_index("activity_id_int")
)

interactions = interactions.join(activity_id_map, on="activity_id", how="left")

print(f"{interactions['activity_id_int'].n_unique()} unique activities")
print(interactions.select(["exercise_id", "activity_id", "activity_id_int"]).head())

351 unique activities
shape: (5, 3)
┌─────────────────────────────────┬─────────────────────────────────┬─────────────────┐
│ exercise_id                     ┆ activity_id                     ┆ activity_id_int │
│ ---                             ┆ ---                             ┆ ---             │
│ str                             ┆ str                             ┆ u32             │
╞═════════════════════════════════╪═════════════════════════════════╪═════════════════╡
│ 97516718-fd8f-4f90-8ead-56dff6… ┆ 07144c8b-67d5-4596-b9e3-d49841… ┆ 6               │
│ f90ab87b-7054-4de8-b836-300653… ┆ 0f54e38b-1a89-40aa-ad52-da52ba… ┆ 22              │
│ f90ab87b-7054-4de8-b836-300653… ┆ 0f54e38b-1a89-40aa-ad52-da52ba… ┆ 22              │
│ 21a30e28-d557-4760-a3dd-3838f4… ┆ 0f54e38b-1a89-40aa-ad52-da52ba… ┆ 22              │
│ 21a30e28-d557-4760-a3dd-3838f4… ┆ 0f54e38b-1a89-40aa-ad52-da52ba… ┆ 22              │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────┘

### Build per-student sequences

Group the enriched attempt log by student and collect each field into a parallel list ordered chronologically by `created_at` (converted to a Unix timestamp in seconds). The result is a dict keyed by `user_id_int`, where each value is a dict of lists — one list per field, all of the same length.

In [9]:
# student_sequences = {
#     row["user_id_int"]: {
#         "exercise_id_int":      [a["exercise_id_int"]      for a in row["attempts"]],
#         "exercise_id":          [a["exercise_id"]      for a in row["attempts"]],  
#         "activity_id_int":      [a["activity_id_int"]      for a in row["attempts"]],
#         "activity_id":          [a["activity_id"]      for a in row["attempts"]],
#         "data_correct":         [int(a["data_correct"])     for a in row["attempts"]],
#         "created_at":           [a["created_at"]           for a in row["attempts"]],
#         "data_duration":        [int(a["data_duration"])    for a in row["attempts"]],
#     }
#     for row in (
#         interactions
#         .select(["user_id_int", "exercise_id_int", "exercise_id", "activity_id_int", "activity_id", "data_correct", "created_at", "data_duration"])
#         .with_columns(pl.col("created_at").dt.epoch(time_unit="s").alias("created_at"))
#         .sort(["user_id_int", "created_at"])
#         .group_by("user_id_int", maintain_order=True)
#         .agg(pl.struct(["exercise_id_int", "exercise_id", "activity_id_int", "activity_id", "data_correct", "created_at", "data_duration"]).alias("attempts"))
#         .iter_rows(named=True)
#     )
# }

# print(f"{len(student_sequences)} students")
# uid = next(iter(student_sequences))
# print(f"Example — student {uid}:")
# print({k: v[:2] for k, v in student_sequences[uid].items()})

In [10]:
seq_df = (
    interactions
    .select([
        "user_id_int", "exercise_id_int", "exercise_id",
        "activity_id_int", "activity_id", "data_correct",
        "created_at", "data_duration",
        "work_mode", "data_answer", "session_id", "module_name",  # extras you want in history
    ])
    .with_columns(pl.col("created_at").dt.epoch(time_unit="s").alias("created_at"))
    .sort(["user_id_int", "created_at"])
    .group_by("user_id_int", maintain_order=True)
    .agg(pl.struct([
        "exercise_id_int", "exercise_id", "activity_id_int", "activity_id",
        "data_correct", "created_at", "data_duration",
        "work_mode", "data_answer", "session_id", "module_name",
    ]).alias("attempts"))
)

In [11]:
seq_df.head(2)

shape: (2, 2)
┌─────────────┬─────────────────────────────────┐
│ user_id_int ┆ attempts                        │
│ ---         ┆ ---                             │
│ u32         ┆ list[struct[11]]                │
╞═════════════╪═════════════════════════════════╡
│ 0           ┆ [{3197,"77a65f22-ef59-4958-8c0… │
│ 1           ┆ [{3706,"8991a32c-eb0e-11ec-8fe… │
└─────────────┴─────────────────────────────────┘

In [12]:
seq_df.write_parquet(SAVE_FOLDER / "sequences.parquet")

# --- static exercise metadata, untouched ---
exercises.write_parquet(SAVE_FOLDER / "exercises.parquet")

In [15]:
shuffled = seq_df.sample(fraction=1.0, shuffle=True, seed=42)
n_val = int(len(shuffled) * 0.2)

val_df = shuffled[:n_val]
train_df = shuffled[n_val:]

train_df.write_parquet(SAVE_FOLDER / "train_sequences.parquet")
val_df.write_parquet(SAVE_FOLDER / "val_sequences.parquet")

In [16]:
train_df.shape

(30816, 2)

In [17]:
val_df.shape

(7704, 2)